name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Go 1.15.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
        id: go
      
      - name: Configure AWS Credentials and Config
        env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: | 
          # prepare aws directory
          mkdir ~/.aws
          # write aws config
          echo "[default]" > ~/.aws/config
          echo "region=ap-southeast-1" >> ~/.aws/config
          echo "output=json" >> ~/.aws/config
          # write aws credentials
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
      
      - name: Deploy to AWS
        env: 
            VPCID: ${{ secrets.VPCID }}
        run: | 
          aws cloudformation deploy \
            --region ap-southeast-1 \
            --template-file ./cloudformation/demo-ec2.yml \
            --stack-name demo-ec2 \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              VPCID=$VPCID
      